modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 2 (GPLv2)"

[[mods]]
modId="minetts"
version="0.0.19a"
displayName="TTSmod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="WinLinuxMan, Nick Hammerich"

[[dependencies.minetts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




